#!/bin/bash

ultsvc=/etc/systemd/system/ultimo.service

if [[ -f "$ultsvc" ]] 
then
sudo systemctl start ultimo.service
else
sudo cp ./home/administrator/ultimo/ultimo.service /etc/systemd/system/
sudo chmod +x ./home/administrator/ultimo/app/Ultimo.ICondo.WebApi
sudo systemctl enable ultimo.service
sudo systemctl start ultimo.service
sudo rm -rf ~/.cache/mozilla/firefox/*
fi
